# Generated by Django 4.0 on 2024-04-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom:'),
        ),
        migrations.AlterField(
            model_name='study',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom:'),
        ),
    ]
