# Generated by Django 4.0 on 2024-03-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_center.school', verbose_name='Auteur'),
        ),
    ]
