# Generated by Django 5.0.2 on 2024-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Ecole'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Filière'},
        ),
        migrations.AlterField(
            model_name='school',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Nom:'),
        ),
        migrations.AlterField(
            model_name='study',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Nom:'),
        ),
    ]
