# Étape 1: Utiliser une image Node
FROM node:20


# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY package.json package-lock.json ./

# Installer les dépendances
RUN npm install -g npm
RUN npm install

# Copier le reste des fichiers
COPY . .

# Exposer le port 5173 (React Dev Server)
EXPOSE 5173

# Commande pour démarrer le serveur de développement
CMD ["npm", "run", "dev"]
