version: '3.8'

services:
  web:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DOCKER_BUILDKIT=1
      network: host
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    container_name: nginx
    restart: on-failure
    image: nginx:latest
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./uploads:/app/uploads
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    container_name: postgres
    image: postgres:13
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.4
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
