# Generated by Django 5.0.6 on 2024-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0001_initial'),
        ('core_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom de la Promo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact'),
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('study', 'year')},
        ),
    ]
