# Generated by Django 4.0 on 2024-04-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_center', '0002_alter_school_label_alter_study_label'),
        ('core_author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_center.school', verbose_name='Filière'),
        ),
    ]
