# Generated by Django 5.0.6 on 2024-10-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_peer', to='core_author.student'),
        ),
    ]
