# Generated by Django 4.0 on 2024-03-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_center', '0002_study_school'),
        ('core_author', '0002_alter_professor_school_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='ttype',
        ),
        migrations.AddField(
            model_name='service',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_center.school'),
        ),
    ]
