# Generated by Django 5.0.6 on 2024-10-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0002_user_validation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Personnel'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
    ]
