# Generated by Django 5.0.2 on 2024-03-03 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0002_alter_student_level_choices_alter_student_study'),
        ('core_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peer',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AddField(
            model_name='peer',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Peer/'),
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peer',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Nom de la Promo'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='related_peer', to='core_author.student', verbose_name='Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_center.study', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='year',
            field=models.DateField(verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255, verbose_name='Service')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Service/')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
