# Generated by Django 4.0 on 2024-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_center', '0002_alter_school_label_alter_study_label'),
        ('core_author', '0002_peer_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='study',
            field=models.ManyToManyField(to='core_center.Study', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='professor',
            name='study',
            field=models.ManyToManyField(to='core_center.Study', verbose_name='Filière'),
        ),
    ]
