# Generated by Django 5.0.2 on 2024-03-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0003_alter_peer_options_peer_cover_user_follows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core_author.peer'),
        ),
    ]
