# Generated by Django 4.0 on 2024-04-01 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0003_remove_service_ttype_service_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='follows',
            field=models.ManyToManyField(related_name='P_followed_by', to=settings.AUTH_USER_MODEL, verbose_name='Abonnés'),
        ),
        migrations.AlterField(
            model_name='service',
            name='follows',
            field=models.ManyToManyField(related_name='S_followed_by', to=settings.AUTH_USER_MODEL, verbose_name='Abonnés'),
        ),
    ]
