# Generated by Django 5.0.2 on 2024-03-03 14:25

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0004_alter_student_peer'),
        ('core_center', '0002_alter_school_options_alter_study_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peer',
            options={'verbose_name': 'Promotion'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Etudiant'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_year',
        ),
        migrations.AddField(
            model_name='student',
            name='bac_year',
            field=models.DateField(blank=True, null=True, verbose_name='Année du bac'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_choices',
            field=models.CharField(choices=[('ts', 'TS'), ('eng', 'eng')], max_length=5, null=True, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='student',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core_author.peer', verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core_center.school', verbose_name='Ecole'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core_center.study', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.user_directory_path, verbose_name='Image Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL, verbose_name='Abonné'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='est actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='est staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='est admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_choice',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('personnel', 'Personnel')], max_length=10, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Nom Utilisateur'),
        ),
    ]
