# Generated by Django 5.0.2 on 2024-03-03 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0005_alter_peer_options_alter_student_options_and_more'),
        ('core_center', '0002_alter_school_options_alter_study_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professeur'},
        ),
        migrations.AlterField(
            model_name='peer',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='related_peer', to='core_author.student', verbose_name='Gerant'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='school',
            field=models.ManyToManyField(to='core_center.school', verbose_name='ecole'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='matière'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Service/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='service',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gerant'),
        ),
    ]
