# Generated by Django 5.0.2 on 2024-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0006_alter_professor_options_alter_peer_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level_choices',
            field=models.CharField(choices=[('ts', 'ts'), ('eng', 'eng')], max_length=5, null=True, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_choice',
            field=models.CharField(choices=[('student', 'student'), ('professor', 'professor'), ('personnel', 'personnel')], max_length=10, verbose_name='statut'),
        ),
    ]
