# Generated by Django 5.0.2 on 2024-03-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0007_alter_student_level_choices_alter_user_status_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core_author.user',),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='services_followed', to=settings.AUTH_USER_MODEL, verbose_name='Abonnes'),
        ),
        migrations.AddField(
            model_name='service',
            name='ttype',
            field=models.CharField(blank=True, choices=[('communnuty', 'communaute'), ('administration', 'administration')], max_length=255, null=True, verbose_name='type de service'),
        ),
    ]
