# Generated by Django 5.0.2 on 2024-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0008_personnel_service_description_service_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='administration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ttype',
            field=models.CharField(blank=True, choices=[('communnuty', 'COMMUNAUTE'), ('administration', 'ADMINISTRATION')], max_length=255, null=True, verbose_name='type de service'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_choices',
            field=models.CharField(choices=[('ts1', 'TS1'), ('ts2', 'TS2'), ('ts3', 'TS3'), ('eng1', 'ING1'), ('eng2', 'ING2'), ('eng3', 'ING3'), ('master1', 'Master1'), ('master2', 'Master2')], max_length=10, null=True, verbose_name='Niveau'),
        ),
    ]
