# Generated by Django 5.0.2 on 2024-03-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0009_personnel_administration_alter_service_ttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status_choice',
        ),
    ]
