# Generated by Django 5.0.2 on 2024-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0011_alter_peer_manager_alter_user_follows_peeruser'),
        ('core_content', '0006_alter_event_options_event_label_alter_event_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peeruser',
            options={'verbose_name': 'EtudiantPromo'},
        ),
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_content.postuser'),
        ),
    ]
