# Generated by Django 5.0.2 on 2024-03-16 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0001_initial'),
        ('core_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpeer',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core_author.peer', verbose_name='Promotion'),
        ),
    ]
