# Generated by Django 5.0.2 on 2024-03-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpost',
            name='post_type',
            field=models.CharField(choices=[('UserPost', 'Utilisateur Publication'), ('PostService', 'Service Publication'), ('PostPeer', 'Promo Publication')], max_length=20, null=True, verbose_name='Type de fichier'),
        ),
        migrations.AddField(
            model_name='postservice',
            name='ttype',
            field=models.CharField(choices=[('COMMUNITY', 'Communautaire'), ('administration', 'Administration')], max_length=20, null=True, verbose_name='Type de fichier'),
        ),
    ]
