# Generated by Django 4.0 on 2024-04-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0003_personnel_study_professor_study'),
        ('core_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core_author.service'),
        ),
    ]
