# Generated by Django 5.0.6 on 2024-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpost',
            name='source',
            field=models.CharField(choices=[('etudiant', 'ETUDIANT'), ('professeur', 'PROFESSEUR'), ('personnel', 'PERSONNEL'), ('service', 'SERVICE'), ('promotion', 'PROMOTION'), ('autre', 'AUTRE')], max_length=10, null=True, verbose_name='source'),
        ),
    ]
