# Generated by Django 5.0.2 on 2024-03-03 13:30

import core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_author', '0003_alter_peer_options_peer_cover_user_follows_and_more'),
        ('core_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content_type', models.CharField(choices=[('RAW_TEXT', 'Raw Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10, verbose_name='Type de fichier')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.get_upload_path, verbose_name='Fichier')),
                ('description', models.TextField()),
                ('edited', models.BooleanField(default=False, verbose_name='edité?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('likes', models.ManyToManyField(blank=True, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication Utilisateurs',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_content.postuser'),
        ),
        migrations.CreateModel(
            name='PostPeer',
            fields=[
                ('postuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_content.postuser')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core_author.peer', verbose_name='Promotion')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_content.postuser',),
        ),
        migrations.CreateModel(
            name='PostService',
            fields=[
                ('postuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_content.postuser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core_author.service', verbose_name='Service')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_content.postuser',),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
