# Generated by Django 5.0.6 on 2024-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_content', '0002_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='content_type',
            field=models.CharField(choices=[('IMAGE POST', 'Image Post'), ('RICH POST', 'Rich Post'), ('SIMPLE POST', 'Simple Post')], max_length=15, null=True, verbose_name='Type de post'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre'),
        ),
    ]
