# Generated by Django 5.0.2 on 2024-03-22 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_content', '0002_generalpost_post_type_postservice_ttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpost',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='postpeer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postservice',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postuser',
            name='content_type',
        ),
        migrations.AddField(
            model_name='generalpost',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
