# Generated by Django 5.0.2 on 2024-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_content', '0004_alter_postpeer_options_alter_postservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
