# Generated by Django 4.0 on 2024-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_content', '0004_remove_generalpost_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postservice',
            name='ttype',
        ),
        migrations.AddField(
            model_name='postpeer',
            name='content_type',
            field=models.CharField(choices=[('RAW_TEXT', 'Raw Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10, null=True, verbose_name='Type de fichier'),
        ),
        migrations.AddField(
            model_name='postservice',
            name='content_type',
            field=models.CharField(choices=[('RAW_TEXT', 'Raw Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10, null=True, verbose_name='Type de fichier'),
        ),
        migrations.AddField(
            model_name='postuser',
            name='content_type',
            field=models.CharField(choices=[('RAW_TEXT', 'Raw Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10, null=True, verbose_name='Type de fichier'),
        ),
    ]
