# Generated by Django 5.0.2 on 2024-03-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_content', '0005_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evénement'},
        ),
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu'),
        ),
    ]
