name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backendProject/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/projet/backend
            git pull origin main
            docker-compose down
            docker-compose -f docker-compose.prod.yml up -d --build
            docker system prune -f 